Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -18,6 +18,13 @@ jobs:
           curl -o structurizr-cli.zip -L https://github.com/structurizr/cli/releases/download/v1.35.0/structurizr-cli-1.35.0.zip
           unzip structurizr-cli.zip
           cp $(find . -name "structurizr-cli-*.jar" -type f) $GITHUB_WORKSPACE/structurizr-cli.jar
+      - run: |
+          if [[ ! -f $GITHUB_WORKSPACE/structurizr-cli.jar || -z $(file $GITHUB_WORKSPACE/structurizr-cli.jar | grep Zip) ]]; then
+            echo "Structurizr CLI jar download incomplete or invalid."
+            exit 1
+          fi
+      - run: echo "Classpath: $CLASSPATH"
+      - run: echo "CLI jar path: $GITHUB_WORKSPACE/structurizr-cli.jar"
       - run: mkdir -p mermaid
       - run: |
           for dsl_file in $(find . -name "*.dsl"); do
